authner/src/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    # post views
    path('', views.post_list, name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/',
        views.post_detail,
        name='post_detail'),
    path('tag/<slug:tag_slug>/',
         views.post_list, name='post_list_by_tag'),
]

authner/src/blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager
from tinymce.models import HTMLField

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')

class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title       = models.CharField(max_length=250)
    slug        = models.SlugField(
                    max_length=250,
                    unique_for_date='publish')
    author      = models.ForeignKey(
                    User,
                    on_delete=models.CASCADE,
                    related_name='blog_posts')
    body        = models.TextField()
    htmlbody    = HTMLField()
    publish     = models.DateTimeField(default=timezone.now)
    created     = models.DateTimeField(auto_now_add=True)
    updated     = models.DateTimeField(auto_now=True)
    status      = models.CharField(
                    max_length=10,
                    choices=STATUS_CHOICES,
                    default='draft')
    objects     = models.Manager()
    published   = PublishedManager()
    tags        = TaggableManager()

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail',
            args=[self.publish.year,
            self.publish.month,
            self.publish.day,
            self.slug])

class Comment(models.Model):
    post        = models.ForeignKey(Post,
        on_delete=models.CASCADE,
        related_name='comments')
    name        = models.CharField(max_length=80)
    email       = models.EmailField()
    body        = models.TextField()
    htmlbody    = HTMLField()
    created     = models.DateTimeField(auto_now_add=True)
    updated     = models.DateTimeField(auto_now=True)
    active      = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return 'Comment by {} on {}'.format(self.name, self.post)

authner/src/blog/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model   = Comment
        fields  = ('name', 'email', 'body')

authner/src/blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, Comment
from .forms import CommentForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from taggit.models import Tag
from django.db.models import Count

def post_list(request, tag_slug=None):
    object_list = Post.published.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])
    paginator = Paginator(object_list, 3)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    return render(request,
        'blog/post/list.html',
        {'page': page, 
         'posts': posts,
         'tag': tag})

def post_detail(request, year, month, day, post):
    p = get_object_or_404(Post,
        slug=post,
        status='published',
        publish__year=year,
        publish__month=month,
        publish__day=day)
    
    # List of active comments
    comments = p.comments.filter(active=True)
    new_comment = None
    if request.method == 'POST':
        # A comment was POSTed
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Create comment object but don't save to db yet
            new_comment = comment_form.save(commit=False)
            new_comment.post = p
            # Save comment to db
            new_comment.save()
    else:
        comment_form = CommentForm()
    
    # similar post by tag sharing
    post_tag_ids    = p.tags.values_list('id', flat=True)
    similar_posts   = Post.published.filter(tags__in=post_tag_ids).exclude(id=p.id)
    similar_posts   = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags','-publish')[:4] 
    return render(request,
        'blog/post/detail.html',
        {'post': p,
         'comments': comments,
         'new_comment': new_comment,
         'comment_form': comment_form,
         'similar_posts': similar_posts})

authner/src/blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
<h1>{{ post.title }}</h1>

<p class="date">
    Published {{ post.publish }} by {{ post.author }}
</p>

{{ post.body|linebreaks }}

{% autoescape off %}{{ post.htmlbody }}{% endautoescape %}

<p class="tags">
    {% for tag in post.tags.all %}
    <a href="{% url "blog:post_list_by_tag" tag.slug %}">
        {{ tag.name }}
    </a>
    {% endfor %}
</p>

{% with similar_posts.count as nsimilar %}
{% if nsimilar > 0 %}
<h2>and also:</h2>
<ul>
{% for post in similar_posts %}
<li><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></li>
{% endfor %}
</ul>
{% endif %}
{% endwith %}

<hr />

{% with comments.count as total_comments %}
{% if total_comments > 0 %}
<h2>
    {{ total_comments }} comment{{ total_comments|pluralize }}
</h2>
{% else %}
No comments (yet).
{% endif %}
{% endwith %}

{% for comment in comments %}
<div class="comment">
    <p class="info">
        Comment {{ forloop.counter }} by {{ comment.name }}
        {{ comment.created }}
    </p>
    {{ comment.body|linebreaks }}
</div>
{% endfor %}

{% if new_comment %}
<h2>Your comment has been added.</h2>
{% else %}
<h2>Add new comment</h2>
<form action="." method="post">
    {{ comment_form.as_p }}
    {% csrf_token %}
    <p><input type="submit" value="Add comment"></p>
</form>
{% endif %}

{% endblock %}

authner/src/blog/templates/blog/post/list.html
{% extends "blog/base.html" %}

{% block title %}last in...{% endblock %}

{% block content %}
<h1 class="welcome">Whatever comes first</h1>
{% if tag %}
<h2>What I have to say about <em>{{ tag.name }}</em>:</h2>
{% endif %}
{% for post in posts %}
<div class="post-header">
    <h2 class="title">
        <a href="{{ post.get_absolute_url }}">
            {{ post.title }}
        </a>
    </h2>
    <p class="tags">
        {% for tag in post.tags.all %}
        <a href="{% url "blog:post_list_by_tag" tag.slug %}">
            {{ tag.name }}
        </a>
        {% endfor %}
    </p>
</div>
<p class="date">Published {{ post.publish }} bij {{ post.author }}</p>
<div class="post-body">
    {{ post.body|truncatewords:30|linebreaks }}
</div>
{% endfor %}

{% include "pagination.html" with page=posts %}

{% endblock %}